rongcloud:
  app_key: kj7swf8ok1xh2
  app_secret: RgEfcuQjWkuJ

jpush:
  appkey:
  master_secret:

redis:
  host: 127.0.0.1
  #password: estate
  port: 26379
  expires_in: 5400
  cache: 1
  queue: 0
  object_db: 3

logs:
  jpush: log/jpush.log

aliyun:
  access_key_id: LTAIXiGggqWgevcM
  access_key_secret: CWJDxUrWR9fwI4qVlLjBYFCQij5xuF
  bucket: kuajinghelp
  endpoint: oss-cn-beijing.aliyuncs.com
